[workspace]
members = [
    "eureka-sink-postgres/db",
    "substreams-sink",
    "substreams/eth-block-header",
    "substreams/eth-balance"
    ]

[profile.release]
opt-level = 2
# todo: set proper profile options https://doc.rust-lang.org/cargo/reference/profiles.html
