firehose_endpoint = "https://mainnet.eth.streamingfast.io:443"
package_file_name = "./eth-blockheaders-v0.1.0.spkg"
module_name = "block_meta"
start_block = 100
end_block = 10000
postgres_dsn = "postgres://dev-node:insecure-change-me-in-prod@localhost:5432/dev-node?sslmode=disable"
schema_file_name = "./schema.sql"
schema = "ethereummainnet"
