[package]
name = "eureka-cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bigdecimal = "0.3.0"
clap-serde-derive = "0.2.0"
eureka-sink-postgres = { path = "../../../eureka-sink-postgres/db" }
hex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.2"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["net"] }
substreams-sink = { path = "../../../substreams-sink" }
prost = "0.11.6"
blake2 = "0.10.6"

[build-dependencies]
tonic-build = "0.8.4"
