[package]
name = "polygon_lens"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams-ethereum = "0.9.0"
ethabi = "18.0.0"
substreams = "0.5.1"
hex-literal = "0.3.4"
prost = "0.11.6"
serde_json = "1.0"
anyhow = "1.0"

[build-dependencies]
prost-build = "0.11.6"
anyhow = "1.0"
substreams-ethereum = "0.9.0"

[workspace]
